### ISSUE TITLE
Script does not work for seafile < 7.0.0

### ISSUE THREAD

**Issue by BernieO** [klangborste/seafile_rpi_bash_upgrader#5]
https://github.com/klangborste/seafile_rpi_bash_upgrader/commit/2b85b30f200441b1f06cd0b2e6aad4d964c9a169 makes this script unusable for Seafile < 7.0.0.
This is the output of the script trying to upgrade Seafile 6.0.7:
```
/path/to/seafile_rpi_bash_upgrader# ./seafile_updater.sh 
error on validate server version!
```
This is due to a change in the api server response in Seafile 7.0.0 and hardcoded character positions in the script.

The problem is that for seafile < 7.0.0 the variable `${serv_ver}` gets assigned to an empty string in [Line 40](https://github.com/klangborste/seafile_rpi_bash_upgrader/blob/d246b4e16221bf30b7d6742a1828880fc16ae165/seafile_updater.sh#L40), due to the hardcoded position of characters in the awk command - which makes the test in Line 41 positive and thus exiting the script.

For a possible (imho quite failsafe) fix see #3

**Comment by klangborste** [comment]
Hello @BernieO thank you for open this issue and provide a fix at the same time.
The Pull request is now merged in the master.
